name: Tests

on:
  push:
    branches: [ master ]
    paths: [ "src", "Cargo.toml" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: "Run cargo-tarpaulin"
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.25.2"
          args: "--test-threads 1"

      - name: "Upload coverage report to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

        timeout-minutes: 10
