name: Test

on:
  push:
    branches: [ master ]
    paths: [ "src", "Cargo.toml" ]

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Generate code coverage
        run: cargo tarpaulin --all-features --timeout 120 --out xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
